// Auto-generated from WordPress
export default function Post_pes() {
  return (
    <article className="max-w-3xl mx-auto px-6 py-12">
      <header className="mb-8">
        <h1 className="text-3xl font-bold tracking-tight">PES Chapter</h1>
        <time className="text-sm text-gray-500">2012-01-30</time>
      </header>
      <div className="prose prose-lg" dangerouslySetInnerHTML={{ __html: `<h2>IEEE North Jersey Section Power &amp; Energy Society Chapter</h2>
<p align="left">Ronald Quade, <em>Chair</em><br />
Ken Oexle, <em>Vice-Chair</em><br />
Michael Miller, <em>Secretary</em><br />
William Magerkurth, <em>Treasurer</em></p>
<p>PES Chapter Website: <a href="http://site.ieee.org/northjersey-pes" rel="noopener noreferrer" target="_blank">http://site.ieee.org/northjersey-pes</a> </p>
<p><a href="http://r1.ieee.org/northjersey/wp-content/uploads/sites/23/2012/01/ieee-power-energy-logo.png"><img loading="lazy" decoding="async" class="alignright size-full wp-image-355008" src="http://r1.ieee.org/northjersey/wp-content/uploads/sites/23/2012/01/ieee-power-energy-logo.png" alt="ieee-power-energy-logo" width="270" height="155" /></a></p>
<p align="justify">The IEEE Power &amp; Energy Society (<a title="PES" href="http://www.ieee-pes.org" target="_blank" rel="noopener noreferrer">PES</a>) is the oldest society of the IEEE, focused on the scientific and engineering knowledge about power and energy.</p>
<h3>Upcoming Events</h3>
<p align="justify">For upcoming events, please check the <a href="http://r1.ieee.org/northjersey/calendar/#action=ai1ec_agenda&amp;ai1ec_post_ids=">calendar</a>. Use the filter to see the Chapter&#8217;s upcoming events. One can also use <a>vTools</a> to check for upcoming meetings.</p>
<h3>Past Events</h3>
<p align="justify">For past events, please check the <a href="http://r1.ieee.org/northjersey/calendar/#action=ai1ec_agenda&amp;ai1ec_page_offset=-1&amp;ai1ec_post_ids=">calendar</a>. Use the filter to see the Chapter&#8217;s past events.</p>
<h3><strong>Highlights – 2019</strong></h3>
<p align="justify">In 2019, the PES Chapter held nine technical one-day seminars and two technical/administrative meetings. More than 650 members and non-members attended the events. Many participants used the option to earn Continuing Education Units for attending the seminars, which helped them meet the Professional Engineer Registration requirements in New York and New Jersey. Discussions with Rutgers University were initiated to provide a Professional Ethics Course for PE registration. Two candidates, one with less than 15 years of professional experience and one with more than 15 years of professional experience were identified for the  presentation of the Chapter&#8217;s Outstanding Engineer Award at the IEEE North Jersey Awards Reception in May 2019. The PES Chapter co-organized an Annual PES Life Grade Luncheon in October 2019. The keynote speaker, Russell Harrison, Director, Government Relations, IEEE USA, gave an outstanding presentation on congressional priorities scene and their impact on the economy, business, and engineers. Harry Roman, a Life Senior member and longtime volunteer, actively participated in STEM activities and gave several presentations on New Jersey, the Invention State at elementary schools and high schools. The PES Chapter promoted and facilitated Senior Member Grade advancement.  A Region 1 Award was presented to the PES Chapter Chair, Ronald W. Quade, and another Region 1 Award was presented to Michael Miller, the PES Secretary. Ken Oexle, the PES Chapter&#8217;s Vice-Chair, received the prestigious IEEE MGA Sustained Leadership Award in 2019.</p>
<h3><strong>Highlights – 2018</strong></h3>
<p align="justify">In 2018, the PES Chapter organized ten technical one-day seminars and three technical/administrative meetings. More than 600 members and non-members were in attendance. Many participants used the option to earn Continuing Education Units for attending the seminars, which helped them meet the Professional Engineer Registration requirements in New York and New Jersey.  The Chapter worked with IEEE TAB to present a seminar on Smart Power Grids at NJIT and partnered with Rutgers University to provide a Professional Ethics Course for PE registration. A candidate for the Chapter’s Outstanding Engineer Award was identified, and the award will be presented at the Section&#8217;s Awards Reception in May 2019. The chapter also provided comments on the PES Corporate Engagement program. The Chapter held the Annual PES Life Grade luncheon featuring a technical presentation by a member of the chapter titled <em>Energy Strong</em>, providing an overview of utility strategies to address future needs of the aging infrastructure and improved reliability performance.  Harry Roman (Life Senior Member) contributed to STEM activities with a presentation on <em>New Jersey &#8211; the Invention State</em>, which is now being incorporated in elementary and high school curricula. The Chapter continued to promote Senior Member Grade advancement.  The Chapter also provided funding and guidance for a solar car project and assessed the viability of a 2019 Drone Conference at New Jersey Institute of Technology.</p>
<h3><strong>Highlights – 2017</strong></h3>
<p align="justify">In 2017, the Chapter has expanded its offering of excellent technical programs to 14 events, actively supporting IEEE Milestone nomination activities, and has improved in the area of Educational offerings. It has bolstered student activities and the appointed Vice-Chair and Treasurer have championed many new functions and programs along with a follow-through on our distribution and advertising.  Public Affairs and Membership related goals were maintained at the same level of excellence and special additions were made.  The North New Jersey Chapter hosted fourteen programs with a total attendance of 626 or an average of 48 attendees per meeting.  The selection of programs is on technical quality, value, and the expertise of the speaker in their given field.  This is a continuation of a multi-year ongoing effort.</p>
<h3><strong>Highlights &#8211; 2016</strong></h3>
<p align="justify">In 2016, the PES Chapter held 10 technical full-day seminars with continuing education units offered for Professional Engineer Registration requirements in both New Jersey and New York. More than 550 people attended the seminars. The chapter held three additional meetings. On Sunday May 1, 2016, the PES Chapter presented the Chapter&#8217;s Outstanding Engineers Award at the IEEE North Jersey Section Awards Banquet. The Chapter helped to coordinate a dedication ceremony for the IEEE milestone &#8220;Weston Meters&#8221; on Sep. 23, 2016 at New Jersey Institute of Technology [<a href="http://ethw.org/Milestones:Weston_Meters">link</a>], which was attended by 78 participants. The Chapter also co-organized the annual IEEE Life Grade Luncheon, which was attended by 38 participants.</p>
<h3><strong>Highlights &#8211; 2015</strong></h3>
<p align="justify">In 2015, the PES Chapter held 12 technical full-day seminars with continuing education units offered for Professional Engineer Registration requirements in both New York and New Jersey. The chapter held one additional technical meeting. Nearly 700 persons attended the PES Chapter activities in 2015. The Chapter nominated a candidate for the PES Chapter Outstanding Engineer Award and presented a plaque at the Annual Awards Reception to William Magerkurth on May 3, 2015. The Chapter identified another candidate, James Hubertus, who was approved by PES for presentation of the Chapter&#8217;s Outstanding Engineer Award at our Awards Reception on May 1, 2016. The Chapter organized the Annual PES Life Grade luncheon, featuring a Life Senior Member technical speaker on PES STEM Activities within the North Jersey PES Chapter. The PES Chapter recognized Virginia Sulzberger, PES Life Fellow, who was admitted to the National Academy of Engineers. The Chapter promoted and facilitated activities to elevate members to the Senior Member Grade. It assisted in reviewing the IEEE Milestone Weston Nomination at the New Jersey Institute of Technology which was approved by the IEEE Board of Directors in November 2015.</p>
<h3><strong>Highlights &#8211; 2014</strong></h3>
<p align="justify">In 2014, the PES Chapter held five one-day technical seminars. The topics for the technical seminars included: GIS Analytic Systems, Metering, Generator Protection, Bushings and Transformer Protection. The Chapter nominated a Chapter Outstanding Engineer candidate and scheduled a Life Grade Luncheon. It also participated in Senior Member Grade elevation drives and IEEE Milestone site nomination and dedication ceremonies.</p>
<h3><strong>Highlights &#8211; 2013</strong></h3>
<ul>
<li>The PES Chapter conducted five technical one-day seminars with continuing education units offered for Professional Engineer Registration requirements in both New York and New Jersey.</li>
<li>The PES Chapter nominated a candidate for the PES Chapter Outstanding Engineer Award and presented the plaque at the Annual Awards Reception.</li>
<li>The PES Chapter identified another candidate, and nominated this candidate in November 2013 for presentation of the Chapter&#8217;s Outstanding Engineer Award in 2014.</li>
<li>The PES Chapter held an Annual Life Grade luncheon featuring a technical speaker from the IEEE History Center at Rutgers University in New Jersey who presented a program on the history and technical contributions at Bell Laboratory facilities in New Jersey.</li>
<li>Members of the PES Chapter promoted and facilitated programs to elevate members to the Senior Member Grade on June 5, 2013 at Bell Laboratories, Alcatel-Lucent and on November 6, 2013 at the Clifton Public Library. Several members were successfully endorsed to the Senior Member Grade Level.</li>
<li>The PES Chapter promoted seminars and registered participants using IEEE vTools. In total, 399 persons attended our activities in 2013. The Chapter honored and recognized two new PES Fellows of the Class of 2013 &#8211; Dr Peter Balma and Dr Bruce Fardanesh, and was the host Chapter for the PES Plain Talk Conference held in Seacaucus, NJ on March 5-7, 2013.</li>
</ul>
` }} />
    </article>
  );
}
